/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fconstraints_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[59] = {55, 1, 0, 55, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54};
static const casadi_int casadi_s1[37] = {33, 1, 0, 33, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32};

/* fconstraint:(i0[55])->(o0[33]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a5, a6, a7, a8, a9;
    a0=8.5000000000000000e+00;
    a1=arg[0] ? arg[0][0] : 0;
    a2=(a0*a1);
    a3=-1.0472135954999581e+01;
    a4=arg[0] ? arg[0][3] : 0;
    a5=(a3*a4);
    a2=(a2+a5);
    a5=2.8944271909999162e+00;
    a6=arg[0] ? arg[0][6] : 0;
    a7=(a5*a6);
    a2=(a2+a7);
    a7=-1.5278640450004206e+00;
    a8=arg[0] ? arg[0][9] : 0;
    a9=(a7*a8);
    a2=(a2+a9);
    a9=1.1055728090000840e+00;
    a10=arg[0] ? arg[0][12] : 0;
    a11=(a9*a10);
    a2=(a2+a11);
    a11=-5.0000000000000000e-01;
    a12=arg[0] ? arg[0][15] : 0;
    a13=(a11*a12);
    a2=(a2+a13);
    a13=2.5000000000000000e-01;
    a14=arg[0] ? arg[0][33] : 0;
    a15=arg[0] ? arg[0][2] : 0;
    a16=cos(a15);
    a16=(a14*a16);
    a17=arg[0] ? arg[0][34] : 0;
    a18=cos(a17);
    a16=(a16*a18);
    a16=(a13*a16);
    a2=(a2-a16);
    if (res[0]!=0) res[0][0]=a2;
    a2=arg[0] ? arg[0][1] : 0;
    a16=(a0*a2);
    a18=arg[0] ? arg[0][4] : 0;
    a19=(a3*a18);
    a16=(a16+a19);
    a19=arg[0] ? arg[0][7] : 0;
    a20=(a5*a19);
    a16=(a16+a20);
    a20=arg[0] ? arg[0][10] : 0;
    a21=(a7*a20);
    a16=(a16+a21);
    a21=arg[0] ? arg[0][13] : 0;
    a22=(a9*a21);
    a16=(a16+a22);
    a22=arg[0] ? arg[0][16] : 0;
    a23=(a11*a22);
    a16=(a16+a23);
    a23=sin(a15);
    a23=(a14*a23);
    a24=cos(a17);
    a23=(a23*a24);
    a23=(a13*a23);
    a16=(a16-a23);
    if (res[0]!=0) res[0][1]=a16;
    a16=(a0*a15);
    a23=arg[0] ? arg[0][5] : 0;
    a24=(a3*a23);
    a16=(a16+a24);
    a24=arg[0] ? arg[0][8] : 0;
    a25=(a5*a24);
    a16=(a16+a25);
    a25=arg[0] ? arg[0][11] : 0;
    a26=(a7*a25);
    a16=(a16+a26);
    a26=arg[0] ? arg[0][14] : 0;
    a27=(a9*a26);
    a16=(a16+a27);
    a27=arg[0] ? arg[0][17] : 0;
    a28=(a11*a27);
    a16=(a16+a28);
    a17=sin(a17);
    a14=(a14*a17);
    a14=(a13*a14);
    a16=(a16-a14);
    if (res[0]!=0) res[0][2]=a16;
    a16=2.6180339887498953e+00;
    a14=(a16*a1);
    a17=-1.1708203932499370e+00;
    a28=(a17*a4);
    a14=(a14+a28);
    a28=-2.;
    a29=(a28*a6);
    a14=(a14+a29);
    a29=8.9442719099991586e-01;
    a30=(a29*a8);
    a14=(a14+a30);
    a30=-6.1803398874989479e-01;
    a31=(a30*a10);
    a14=(a14+a31);
    a31=2.7639320225002101e-01;
    a32=(a31*a12);
    a14=(a14+a32);
    a32=arg[0] ? arg[0][35] : 0;
    a33=cos(a23);
    a33=(a32*a33);
    a34=arg[0] ? arg[0][36] : 0;
    a35=cos(a34);
    a33=(a33*a35);
    a33=(a13*a33);
    a14=(a14-a33);
    if (res[0]!=0) res[0][3]=a14;
    a14=(a16*a2);
    a33=(a17*a18);
    a14=(a14+a33);
    a33=(a28*a19);
    a14=(a14+a33);
    a33=(a29*a20);
    a14=(a14+a33);
    a33=(a30*a21);
    a14=(a14+a33);
    a33=(a31*a22);
    a14=(a14+a33);
    a33=sin(a23);
    a33=(a32*a33);
    a35=cos(a34);
    a33=(a33*a35);
    a33=(a13*a33);
    a14=(a14-a33);
    if (res[0]!=0) res[0][4]=a14;
    a14=(a16*a15);
    a33=(a17*a23);
    a14=(a14+a33);
    a33=(a28*a24);
    a14=(a14+a33);
    a33=(a29*a25);
    a14=(a14+a33);
    a33=(a30*a26);
    a14=(a14+a33);
    a33=(a31*a27);
    a14=(a14+a33);
    a34=sin(a34);
    a32=(a32*a34);
    a32=(a13*a32);
    a14=(a14-a32);
    if (res[0]!=0) res[0][5]=a14;
    a14=-7.2360679774997905e-01;
    a32=(a14*a1);
    a34=2.;
    a33=(a34*a4);
    a32=(a32+a33);
    a33=-1.7082039324993659e-01;
    a35=(a33*a6);
    a32=(a32+a35);
    a35=-1.6180339887498949e+00;
    a36=(a35*a8);
    a32=(a32+a36);
    a36=(a29*a10);
    a32=(a32+a36);
    a36=-3.8196601125010515e-01;
    a37=(a36*a12);
    a32=(a32+a37);
    a37=arg[0] ? arg[0][37] : 0;
    a38=cos(a24);
    a38=(a37*a38);
    a39=arg[0] ? arg[0][38] : 0;
    a40=cos(a39);
    a38=(a38*a40);
    a38=(a13*a38);
    a32=(a32-a38);
    if (res[0]!=0) res[0][6]=a32;
    a32=(a14*a2);
    a38=(a34*a18);
    a32=(a32+a38);
    a38=(a33*a19);
    a32=(a32+a38);
    a38=(a35*a20);
    a32=(a32+a38);
    a38=(a29*a21);
    a32=(a32+a38);
    a38=(a36*a22);
    a32=(a32+a38);
    a38=sin(a24);
    a38=(a37*a38);
    a40=cos(a39);
    a38=(a38*a40);
    a38=(a13*a38);
    a32=(a32-a38);
    if (res[0]!=0) res[0][7]=a32;
    a32=(a14*a15);
    a38=(a34*a23);
    a32=(a32+a38);
    a38=(a33*a24);
    a32=(a32+a38);
    a38=(a35*a25);
    a32=(a32+a38);
    a38=(a29*a26);
    a32=(a32+a38);
    a38=(a36*a27);
    a32=(a32+a38);
    a39=sin(a39);
    a37=(a37*a39);
    a37=(a13*a37);
    a32=(a32-a37);
    if (res[0]!=0) res[0][8]=a32;
    a32=3.8196601125010515e-01;
    a37=(a32*a1);
    a39=-8.9442719099991586e-01;
    a38=(a39*a4);
    a37=(a37+a38);
    a38=1.6180339887498949e+00;
    a40=(a38*a6);
    a37=(a37+a40);
    a40=1.7082039324993681e-01;
    a41=(a40*a8);
    a37=(a37+a41);
    a41=(a28*a10);
    a37=(a37+a41);
    a41=7.2360679774997894e-01;
    a42=(a41*a12);
    a37=(a37+a42);
    a42=arg[0] ? arg[0][39] : 0;
    a43=cos(a25);
    a43=(a42*a43);
    a44=arg[0] ? arg[0][40] : 0;
    a45=cos(a44);
    a43=(a43*a45);
    a43=(a13*a43);
    a37=(a37-a43);
    if (res[0]!=0) res[0][9]=a37;
    a37=(a32*a2);
    a43=(a39*a18);
    a37=(a37+a43);
    a43=(a38*a19);
    a37=(a37+a43);
    a43=(a40*a20);
    a37=(a37+a43);
    a43=(a28*a21);
    a37=(a37+a43);
    a43=(a41*a22);
    a37=(a37+a43);
    a43=sin(a25);
    a43=(a42*a43);
    a45=cos(a44);
    a43=(a43*a45);
    a43=(a13*a43);
    a37=(a37-a43);
    if (res[0]!=0) res[0][10]=a37;
    a37=(a32*a15);
    a43=(a39*a23);
    a37=(a37+a43);
    a43=(a38*a24);
    a37=(a37+a43);
    a43=(a40*a25);
    a37=(a37+a43);
    a43=(a28*a26);
    a37=(a37+a43);
    a43=(a41*a27);
    a37=(a37+a43);
    a44=sin(a44);
    a42=(a42*a44);
    a42=(a13*a42);
    a37=(a37-a42);
    if (res[0]!=0) res[0][11]=a37;
    a37=-2.7639320225002101e-01;
    a1=(a37*a1);
    a42=6.1803398874989479e-01;
    a4=(a42*a4);
    a1=(a1+a4);
    a6=(a39*a6);
    a1=(a1+a6);
    a8=(a34*a8);
    a1=(a1+a8);
    a8=1.1708203932499357e+00;
    a10=(a8*a10);
    a1=(a1+a10);
    a10=-2.6180339887498936e+00;
    a6=(a10*a12);
    a1=(a1+a6);
    a6=arg[0] ? arg[0][41] : 0;
    a4=cos(a26);
    a4=(a6*a4);
    a44=arg[0] ? arg[0][42] : 0;
    a43=cos(a44);
    a4=(a4*a43);
    a4=(a13*a4);
    a1=(a1-a4);
    if (res[0]!=0) res[0][12]=a1;
    a2=(a37*a2);
    a18=(a42*a18);
    a2=(a2+a18);
    a19=(a39*a19);
    a2=(a2+a19);
    a20=(a34*a20);
    a2=(a2+a20);
    a21=(a8*a21);
    a2=(a2+a21);
    a21=(a10*a22);
    a2=(a2+a21);
    a21=sin(a26);
    a21=(a6*a21);
    a20=cos(a44);
    a21=(a21*a20);
    a21=(a13*a21);
    a2=(a2-a21);
    if (res[0]!=0) res[0][13]=a2;
    a15=(a37*a15);
    a23=(a42*a23);
    a15=(a15+a23);
    a24=(a39*a24);
    a15=(a15+a24);
    a25=(a34*a25);
    a15=(a15+a25);
    a26=(a8*a26);
    a15=(a15+a26);
    a26=(a10*a27);
    a15=(a15+a26);
    a44=sin(a44);
    a6=(a6*a44);
    a6=(a13*a6);
    a15=(a15-a6);
    if (res[0]!=0) res[0][14]=a15;
    a15=(a0*a12);
    a6=arg[0] ? arg[0][18] : 0;
    a44=(a3*a6);
    a15=(a15+a44);
    a44=arg[0] ? arg[0][21] : 0;
    a26=(a5*a44);
    a15=(a15+a26);
    a26=arg[0] ? arg[0][24] : 0;
    a25=(a7*a26);
    a15=(a15+a25);
    a25=arg[0] ? arg[0][27] : 0;
    a24=(a9*a25);
    a15=(a15+a24);
    a24=arg[0] ? arg[0][30] : 0;
    a23=(a11*a24);
    a15=(a15+a23);
    a23=arg[0] ? arg[0][43] : 0;
    a2=cos(a27);
    a2=(a23*a2);
    a21=arg[0] ? arg[0][44] : 0;
    a20=cos(a21);
    a2=(a2*a20);
    a2=(a13*a2);
    a15=(a15-a2);
    if (res[0]!=0) res[0][15]=a15;
    a15=(a0*a22);
    a2=arg[0] ? arg[0][19] : 0;
    a20=(a3*a2);
    a15=(a15+a20);
    a20=arg[0] ? arg[0][22] : 0;
    a19=(a5*a20);
    a15=(a15+a19);
    a19=arg[0] ? arg[0][25] : 0;
    a18=(a7*a19);
    a15=(a15+a18);
    a18=arg[0] ? arg[0][28] : 0;
    a1=(a9*a18);
    a15=(a15+a1);
    a1=arg[0] ? arg[0][31] : 0;
    a4=(a11*a1);
    a15=(a15+a4);
    a4=sin(a27);
    a4=(a23*a4);
    a43=cos(a21);
    a4=(a4*a43);
    a4=(a13*a4);
    a15=(a15-a4);
    if (res[0]!=0) res[0][16]=a15;
    a0=(a0*a27);
    a15=arg[0] ? arg[0][20] : 0;
    a3=(a3*a15);
    a0=(a0+a3);
    a3=arg[0] ? arg[0][23] : 0;
    a5=(a5*a3);
    a0=(a0+a5);
    a5=arg[0] ? arg[0][26] : 0;
    a7=(a7*a5);
    a0=(a0+a7);
    a7=arg[0] ? arg[0][29] : 0;
    a9=(a9*a7);
    a0=(a0+a9);
    a9=arg[0] ? arg[0][32] : 0;
    a11=(a11*a9);
    a0=(a0+a11);
    a21=sin(a21);
    a23=(a23*a21);
    a23=(a13*a23);
    a0=(a0-a23);
    if (res[0]!=0) res[0][17]=a0;
    a0=(a16*a12);
    a23=(a17*a6);
    a0=(a0+a23);
    a23=(a28*a44);
    a0=(a0+a23);
    a23=(a29*a26);
    a0=(a0+a23);
    a23=(a30*a25);
    a0=(a0+a23);
    a23=(a31*a24);
    a0=(a0+a23);
    a23=arg[0] ? arg[0][45] : 0;
    a21=cos(a15);
    a21=(a23*a21);
    a11=arg[0] ? arg[0][46] : 0;
    a4=cos(a11);
    a21=(a21*a4);
    a21=(a13*a21);
    a0=(a0-a21);
    if (res[0]!=0) res[0][18]=a0;
    a0=(a16*a22);
    a21=(a17*a2);
    a0=(a0+a21);
    a21=(a28*a20);
    a0=(a0+a21);
    a21=(a29*a19);
    a0=(a0+a21);
    a21=(a30*a18);
    a0=(a0+a21);
    a21=(a31*a1);
    a0=(a0+a21);
    a21=sin(a15);
    a21=(a23*a21);
    a4=cos(a11);
    a21=(a21*a4);
    a21=(a13*a21);
    a0=(a0-a21);
    if (res[0]!=0) res[0][19]=a0;
    a16=(a16*a27);
    a17=(a17*a15);
    a16=(a16+a17);
    a17=(a28*a3);
    a16=(a16+a17);
    a17=(a29*a5);
    a16=(a16+a17);
    a30=(a30*a7);
    a16=(a16+a30);
    a31=(a31*a9);
    a16=(a16+a31);
    a11=sin(a11);
    a23=(a23*a11);
    a23=(a13*a23);
    a16=(a16-a23);
    if (res[0]!=0) res[0][20]=a16;
    a16=(a14*a12);
    a23=(a34*a6);
    a16=(a16+a23);
    a23=(a33*a44);
    a16=(a16+a23);
    a23=(a35*a26);
    a16=(a16+a23);
    a23=(a29*a25);
    a16=(a16+a23);
    a23=(a36*a24);
    a16=(a16+a23);
    a23=arg[0] ? arg[0][47] : 0;
    a11=cos(a3);
    a11=(a23*a11);
    a31=arg[0] ? arg[0][48] : 0;
    a30=cos(a31);
    a11=(a11*a30);
    a11=(a13*a11);
    a16=(a16-a11);
    if (res[0]!=0) res[0][21]=a16;
    a16=(a14*a22);
    a11=(a34*a2);
    a16=(a16+a11);
    a11=(a33*a20);
    a16=(a16+a11);
    a11=(a35*a19);
    a16=(a16+a11);
    a11=(a29*a18);
    a16=(a16+a11);
    a11=(a36*a1);
    a16=(a16+a11);
    a11=sin(a3);
    a11=(a23*a11);
    a30=cos(a31);
    a11=(a11*a30);
    a11=(a13*a11);
    a16=(a16-a11);
    if (res[0]!=0) res[0][22]=a16;
    a14=(a14*a27);
    a16=(a34*a15);
    a14=(a14+a16);
    a33=(a33*a3);
    a14=(a14+a33);
    a35=(a35*a5);
    a14=(a14+a35);
    a29=(a29*a7);
    a14=(a14+a29);
    a36=(a36*a9);
    a14=(a14+a36);
    a31=sin(a31);
    a23=(a23*a31);
    a23=(a13*a23);
    a14=(a14-a23);
    if (res[0]!=0) res[0][23]=a14;
    a14=(a32*a12);
    a23=(a39*a6);
    a14=(a14+a23);
    a23=(a38*a44);
    a14=(a14+a23);
    a23=(a40*a26);
    a14=(a14+a23);
    a23=(a28*a25);
    a14=(a14+a23);
    a23=(a41*a24);
    a14=(a14+a23);
    a23=arg[0] ? arg[0][49] : 0;
    a31=cos(a5);
    a31=(a23*a31);
    a36=arg[0] ? arg[0][50] : 0;
    a29=cos(a36);
    a31=(a31*a29);
    a31=(a13*a31);
    a14=(a14-a31);
    if (res[0]!=0) res[0][24]=a14;
    a14=(a32*a22);
    a31=(a39*a2);
    a14=(a14+a31);
    a31=(a38*a20);
    a14=(a14+a31);
    a31=(a40*a19);
    a14=(a14+a31);
    a31=(a28*a18);
    a14=(a14+a31);
    a31=(a41*a1);
    a14=(a14+a31);
    a31=sin(a5);
    a31=(a23*a31);
    a29=cos(a36);
    a31=(a31*a29);
    a31=(a13*a31);
    a14=(a14-a31);
    if (res[0]!=0) res[0][25]=a14;
    a32=(a32*a27);
    a14=(a39*a15);
    a32=(a32+a14);
    a38=(a38*a3);
    a32=(a32+a38);
    a40=(a40*a5);
    a32=(a32+a40);
    a28=(a28*a7);
    a32=(a32+a28);
    a41=(a41*a9);
    a32=(a32+a41);
    a36=sin(a36);
    a23=(a23*a36);
    a23=(a13*a23);
    a32=(a32-a23);
    if (res[0]!=0) res[0][26]=a32;
    a32=(a37*a12);
    a23=(a42*a6);
    a32=(a32+a23);
    a23=(a39*a44);
    a32=(a32+a23);
    a23=(a34*a26);
    a32=(a32+a23);
    a23=(a8*a25);
    a32=(a32+a23);
    a23=(a10*a24);
    a32=(a32+a23);
    a23=arg[0] ? arg[0][51] : 0;
    a36=cos(a7);
    a36=(a23*a36);
    a41=arg[0] ? arg[0][52] : 0;
    a28=cos(a41);
    a36=(a36*a28);
    a36=(a13*a36);
    a32=(a32-a36);
    if (res[0]!=0) res[0][27]=a32;
    a32=(a37*a22);
    a36=(a42*a2);
    a32=(a32+a36);
    a36=(a39*a20);
    a32=(a32+a36);
    a36=(a34*a19);
    a32=(a32+a36);
    a36=(a8*a18);
    a32=(a32+a36);
    a36=(a10*a1);
    a32=(a32+a36);
    a36=sin(a7);
    a36=(a23*a36);
    a28=cos(a41);
    a36=(a36*a28);
    a36=(a13*a36);
    a32=(a32-a36);
    if (res[0]!=0) res[0][28]=a32;
    a37=(a37*a27);
    a42=(a42*a15);
    a37=(a37+a42);
    a39=(a39*a3);
    a37=(a37+a39);
    a34=(a34*a5);
    a37=(a37+a34);
    a8=(a8*a7);
    a37=(a37+a8);
    a10=(a10*a9);
    a37=(a37+a10);
    a41=sin(a41);
    a23=(a23*a41);
    a23=(a13*a23);
    a37=(a37-a23);
    if (res[0]!=0) res[0][29]=a37;
    a37=5.0000000000000000e-01;
    a12=(a37*a12);
    a23=-1.1055728090000840e+00;
    a6=(a23*a6);
    a12=(a12+a6);
    a6=1.5278640450004206e+00;
    a44=(a6*a44);
    a12=(a12+a44);
    a44=-2.8944271909999157e+00;
    a26=(a44*a26);
    a12=(a12+a26);
    a26=1.0472135954999574e+01;
    a25=(a26*a25);
    a12=(a12+a25);
    a25=-8.4999999999999947e+00;
    a24=(a25*a24);
    a12=(a12+a24);
    a24=arg[0] ? arg[0][53] : 0;
    a41=cos(a9);
    a41=(a24*a41);
    a10=arg[0] ? arg[0][54] : 0;
    a8=cos(a10);
    a41=(a41*a8);
    a41=(a13*a41);
    a12=(a12-a41);
    if (res[0]!=0) res[0][30]=a12;
    a22=(a37*a22);
    a2=(a23*a2);
    a22=(a22+a2);
    a20=(a6*a20);
    a22=(a22+a20);
    a19=(a44*a19);
    a22=(a22+a19);
    a18=(a26*a18);
    a22=(a22+a18);
    a1=(a25*a1);
    a22=(a22+a1);
    a1=sin(a9);
    a1=(a24*a1);
    a18=cos(a10);
    a1=(a1*a18);
    a1=(a13*a1);
    a22=(a22-a1);
    if (res[0]!=0) res[0][31]=a22;
    a37=(a37*a27);
    a23=(a23*a15);
    a37=(a37+a23);
    a6=(a6*a3);
    a37=(a37+a6);
    a44=(a44*a5);
    a37=(a37+a44);
    a26=(a26*a7);
    a37=(a37+a26);
    a25=(a25*a9);
    a37=(a37+a25);
    a10=sin(a10);
    a24=(a24*a10);
    a13=(a13*a24);
    a37=(a37-a13);
    if (res[0]!=0) res[0][32]=a37;
    return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int fconstraint(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
    return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT void fconstraint_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void fconstraint_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int fconstraint_n_in(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int fconstraint_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT const char* fconstraint_name_in(casadi_int i){
    switch (i) {
        case 0: return "i0";
        default: return 0;
    }
}

extern "C" CASADI_SYMBOL_EXPORT const char* fconstraint_name_out(casadi_int i){
    switch (i) {
        case 0: return "o0";
        default: return 0;
    }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* fconstraint_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        default: return 0;
    }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* fconstraint_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        default: return 0;
    }
}

extern "C" CASADI_SYMBOL_EXPORT int fconstraint_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 1;
    if (sz_res) *sz_res = 1;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}


