/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int fcost_hessian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
extern "C" void fcost_hessian_incref(void);
extern "C" void fcost_hessian_decref(void);
extern "C" casadi_int fcost_hessian_n_in(void);
extern "C" casadi_int fcost_hessian_n_out(void);
extern "C" const char* fcost_hessian_name_in(casadi_int i);
extern "C" const char* fcost_hessian_name_out(casadi_int i);
extern "C" const casadi_int* fcost_hessian_sparsity_in(casadi_int i);
extern "C" const casadi_int* fcost_hessian_sparsity_out(casadi_int i);
extern "C" int fcost_hessian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
